// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: dfs/dfs.proto

package dfs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DistributedFileSystem_RequestUploadPermission_FullMethodName      = "/dfs.DistributedFileSystem/RequestUploadPermission"
	DistributedFileSystem_UploadFile_FullMethodName                   = "/dfs.DistributedFileSystem/UploadFile"
	DistributedFileSystem_ConfirmUpload_FullMethodName                = "/dfs.DistributedFileSystem/ConfirmUpload"
	DistributedFileSystem_NotifyClientUploadCompletion_FullMethodName = "/dfs.DistributedFileSystem/NotifyClientUploadCompletion"
	DistributedFileSystem_RequestDownloadInfo_FullMethodName          = "/dfs.DistributedFileSystem/RequestDownloadInfo"
	DistributedFileSystem_DownloadFile_FullMethodName                 = "/dfs.DistributedFileSystem/DownloadFile"
	DistributedFileSystem_SendHeartbeat_FullMethodName                = "/dfs.DistributedFileSystem/SendHeartbeat"
	DistributedFileSystem_InitiateReplication_FullMethodName          = "/dfs.DistributedFileSystem/InitiateReplication"
)

// DistributedFileSystemClient is the client API for DistributedFileSystem service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ======= SERVICE DEFINITIONS =======
type DistributedFileSystemClient interface {
	// Client requests permission to upload a file (gets an available Data Keeper)
	RequestUploadPermission(ctx context.Context, in *UploadPermissionRequest, opts ...grpc.CallOption) (*UploadPermissionResponse, error)
	// Client uploads file to the assigned Data Keeper
	UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error)
	// Data Keeper notifies Master Tracker about a successful upload
	ConfirmUpload(ctx context.Context, in *UploadConfirmation, opts ...grpc.CallOption) (*Ack, error)
	// Master Tracker notifies Client that upload is successfully registered
	NotifyClientUploadCompletion(ctx context.Context, in *ClientNotification, opts ...grpc.CallOption) (*Ack, error)
	// Client requests download info (gets list of Data Keepers storing the file)
	RequestDownloadInfo(ctx context.Context, in *DownloadInfoRequest, opts ...grpc.CallOption) (*DownloadInfoResponse, error)
	// Client downloads file from Data Keeper
	DownloadFile(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (*DownloadResponse, error)
	// Data Keeper sends a periodic heartbeat to Master Tracker
	SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*Ack, error)
	// Master Tracker notifies Data Keepers to start a replication process
	InitiateReplication(ctx context.Context, in *ReplicationRequest, opts ...grpc.CallOption) (*Ack, error)
}

type distributedFileSystemClient struct {
	cc grpc.ClientConnInterface
}

func NewDistributedFileSystemClient(cc grpc.ClientConnInterface) DistributedFileSystemClient {
	return &distributedFileSystemClient{cc}
}

func (c *distributedFileSystemClient) RequestUploadPermission(ctx context.Context, in *UploadPermissionRequest, opts ...grpc.CallOption) (*UploadPermissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadPermissionResponse)
	err := c.cc.Invoke(ctx, DistributedFileSystem_RequestUploadPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *distributedFileSystemClient) UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadFileResponse)
	err := c.cc.Invoke(ctx, DistributedFileSystem_UploadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *distributedFileSystemClient) ConfirmUpload(ctx context.Context, in *UploadConfirmation, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, DistributedFileSystem_ConfirmUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *distributedFileSystemClient) NotifyClientUploadCompletion(ctx context.Context, in *ClientNotification, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, DistributedFileSystem_NotifyClientUploadCompletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *distributedFileSystemClient) RequestDownloadInfo(ctx context.Context, in *DownloadInfoRequest, opts ...grpc.CallOption) (*DownloadInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadInfoResponse)
	err := c.cc.Invoke(ctx, DistributedFileSystem_RequestDownloadInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *distributedFileSystemClient) DownloadFile(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (*DownloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadResponse)
	err := c.cc.Invoke(ctx, DistributedFileSystem_DownloadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *distributedFileSystemClient) SendHeartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, DistributedFileSystem_SendHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *distributedFileSystemClient) InitiateReplication(ctx context.Context, in *ReplicationRequest, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, DistributedFileSystem_InitiateReplication_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DistributedFileSystemServer is the server API for DistributedFileSystem service.
// All implementations must embed UnimplementedDistributedFileSystemServer
// for forward compatibility.
//
// ======= SERVICE DEFINITIONS =======
type DistributedFileSystemServer interface {
	// Client requests permission to upload a file (gets an available Data Keeper)
	RequestUploadPermission(context.Context, *UploadPermissionRequest) (*UploadPermissionResponse, error)
	// Client uploads file to the assigned Data Keeper
	UploadFile(context.Context, *UploadFileRequest) (*UploadFileResponse, error)
	// Data Keeper notifies Master Tracker about a successful upload
	ConfirmUpload(context.Context, *UploadConfirmation) (*Ack, error)
	// Master Tracker notifies Client that upload is successfully registered
	NotifyClientUploadCompletion(context.Context, *ClientNotification) (*Ack, error)
	// Client requests download info (gets list of Data Keepers storing the file)
	RequestDownloadInfo(context.Context, *DownloadInfoRequest) (*DownloadInfoResponse, error)
	// Client downloads file from Data Keeper
	DownloadFile(context.Context, *DownloadRequest) (*DownloadResponse, error)
	// Data Keeper sends a periodic heartbeat to Master Tracker
	SendHeartbeat(context.Context, *HeartbeatRequest) (*Ack, error)
	// Master Tracker notifies Data Keepers to start a replication process
	InitiateReplication(context.Context, *ReplicationRequest) (*Ack, error)
	mustEmbedUnimplementedDistributedFileSystemServer()
}

// UnimplementedDistributedFileSystemServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDistributedFileSystemServer struct{}

func (UnimplementedDistributedFileSystemServer) RequestUploadPermission(context.Context, *UploadPermissionRequest) (*UploadPermissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestUploadPermission not implemented")
}
func (UnimplementedDistributedFileSystemServer) UploadFile(context.Context, *UploadFileRequest) (*UploadFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedDistributedFileSystemServer) ConfirmUpload(context.Context, *UploadConfirmation) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmUpload not implemented")
}
func (UnimplementedDistributedFileSystemServer) NotifyClientUploadCompletion(context.Context, *ClientNotification) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyClientUploadCompletion not implemented")
}
func (UnimplementedDistributedFileSystemServer) RequestDownloadInfo(context.Context, *DownloadInfoRequest) (*DownloadInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestDownloadInfo not implemented")
}
func (UnimplementedDistributedFileSystemServer) DownloadFile(context.Context, *DownloadRequest) (*DownloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadFile not implemented")
}
func (UnimplementedDistributedFileSystemServer) SendHeartbeat(context.Context, *HeartbeatRequest) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedDistributedFileSystemServer) InitiateReplication(context.Context, *ReplicationRequest) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateReplication not implemented")
}
func (UnimplementedDistributedFileSystemServer) mustEmbedUnimplementedDistributedFileSystemServer() {}
func (UnimplementedDistributedFileSystemServer) testEmbeddedByValue()                               {}

// UnsafeDistributedFileSystemServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DistributedFileSystemServer will
// result in compilation errors.
type UnsafeDistributedFileSystemServer interface {
	mustEmbedUnimplementedDistributedFileSystemServer()
}

func RegisterDistributedFileSystemServer(s grpc.ServiceRegistrar, srv DistributedFileSystemServer) {
	// If the following call pancis, it indicates UnimplementedDistributedFileSystemServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DistributedFileSystem_ServiceDesc, srv)
}

func _DistributedFileSystem_RequestUploadPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistributedFileSystemServer).RequestUploadPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DistributedFileSystem_RequestUploadPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistributedFileSystemServer).RequestUploadPermission(ctx, req.(*UploadPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistributedFileSystem_UploadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistributedFileSystemServer).UploadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DistributedFileSystem_UploadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistributedFileSystemServer).UploadFile(ctx, req.(*UploadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistributedFileSystem_ConfirmUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadConfirmation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistributedFileSystemServer).ConfirmUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DistributedFileSystem_ConfirmUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistributedFileSystemServer).ConfirmUpload(ctx, req.(*UploadConfirmation))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistributedFileSystem_NotifyClientUploadCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientNotification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistributedFileSystemServer).NotifyClientUploadCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DistributedFileSystem_NotifyClientUploadCompletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistributedFileSystemServer).NotifyClientUploadCompletion(ctx, req.(*ClientNotification))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistributedFileSystem_RequestDownloadInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistributedFileSystemServer).RequestDownloadInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DistributedFileSystem_RequestDownloadInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistributedFileSystemServer).RequestDownloadInfo(ctx, req.(*DownloadInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistributedFileSystem_DownloadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistributedFileSystemServer).DownloadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DistributedFileSystem_DownloadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistributedFileSystemServer).DownloadFile(ctx, req.(*DownloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistributedFileSystem_SendHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistributedFileSystemServer).SendHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DistributedFileSystem_SendHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistributedFileSystemServer).SendHeartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DistributedFileSystem_InitiateReplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistributedFileSystemServer).InitiateReplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DistributedFileSystem_InitiateReplication_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistributedFileSystemServer).InitiateReplication(ctx, req.(*ReplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DistributedFileSystem_ServiceDesc is the grpc.ServiceDesc for DistributedFileSystem service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DistributedFileSystem_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dfs.DistributedFileSystem",
	HandlerType: (*DistributedFileSystemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestUploadPermission",
			Handler:    _DistributedFileSystem_RequestUploadPermission_Handler,
		},
		{
			MethodName: "UploadFile",
			Handler:    _DistributedFileSystem_UploadFile_Handler,
		},
		{
			MethodName: "ConfirmUpload",
			Handler:    _DistributedFileSystem_ConfirmUpload_Handler,
		},
		{
			MethodName: "NotifyClientUploadCompletion",
			Handler:    _DistributedFileSystem_NotifyClientUploadCompletion_Handler,
		},
		{
			MethodName: "RequestDownloadInfo",
			Handler:    _DistributedFileSystem_RequestDownloadInfo_Handler,
		},
		{
			MethodName: "DownloadFile",
			Handler:    _DistributedFileSystem_DownloadFile_Handler,
		},
		{
			MethodName: "SendHeartbeat",
			Handler:    _DistributedFileSystem_SendHeartbeat_Handler,
		},
		{
			MethodName: "InitiateReplication",
			Handler:    _DistributedFileSystem_InitiateReplication_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dfs/dfs.proto",
}
